### ISSUE TITLE
コンテキストメニューに必死チェッカーを追加する

### ISSUE THREAD

**Issue by nodaguti** [chaika/chaika#198]
ContextMenu2ch のように、コンテキストメニューに必死チェッカーを追加する。
Reported by: http://anago.2ch.net/test/read.cgi/software/1359547851/938 など多数

**Comment by foomin10** [comment]
独自に実装する人のためにメモっておきます。

> - 実装が困難
>  - 必死チェッカーの該当ページを取得する方法も少々複雑

IDをbase64エンコードすれば生成できます。

例) `ID:JGApiQ2g0` → `JGApiQ2g0` をBase64エンコード → `SkdBcGlRMmcw`
http://hissi.org/read.php/software/20141106/SkdBcGlRMmcw.html
