### ISSUE TITLE
スレッドリダイレクタがしたらばのスレをスレと認識してない

### ISSUE THREAD

**Issue by foomin10** [chaika/chaika#258]
ex) <http://jbbs.shitaraba.net/bbs/read.cgi/computer/44179/1411987125/>
=> <chaika://board/http://jbbs.shitaraba.net/bbs/read.cgi/computer/44179/1411987125/>

これかな
`return aURL.contains('/test/read.cgi/')`
from [ChaikaURLUtil.js:78](https://github.com/chaika/chaika/blob/1dec8d55e9ceeac893ae944874d8e2ba4229884b/chaika/modules/ChaikaURLUtil.js#L78):in `isThread`
from [ChaikaURLUtil.js:97](https://github.com/chaika/chaika/blob/1dec8d55e9ceeac893ae944874d8e2ba4229884b/chaika/modules/ChaikaURLUtil.js#L97):in `chaikafy`
from [ChaikaRedirector.js:114](https://github.com/chaika/chaika/blob/1dec8d55e9ceeac893ae944874d8e2ba4229884b/chaika/modules/ChaikaRedirector.js#L114):in `shouldLoad`

**Comment by nodaguti** [comment]
報告ありがとうございます。

`read.cgi` が含まれていればスレッドと認識してもいいかもしれないですね...

近日中に修正します。

**Comment by nodaguti** [comment]
- `/read.` を含めばスレッドと判断する
- スレッドとして認識するURLを設定可能にする

http://jbbs.shitaraba.net/bbs/read.cgi/computer/44179/1411987125/153,159
