### ISSUE TITLE
Firefox以外のブラウザだと自動再読み込みが動作しない

### ISSUE THREAD

**Issue by EarlgreyPicard** [chaika/chaika#271]
CyberfoxやSeaMonkeyだとPOSTやスキン変更、あぼーん登録/削除後のスレッド表示の自動再読み込みが動作しません。
報告レス：
http://jbbs.shitaraba.net/bbs/read.cgi/computer/44179/1426703154/660-661
原因：
http://jbbs.shitaraba.net/bbs/read.cgi/computer/44179/1426703154/664

**Comment by nodaguti** [comment]
報告ありがとうございます。
こちらにも書き写さなければと思っていたところでした。

Depends: #264
