### ISSUE TITLE
2ch互換掲示板URLの判定条件検討

### ISSUE THREAD

**Issue by EarlgreyPicard** [chaika/chaika#305]
現状ではchaikaで開きたいURLが開けなかったり、スレッドではないURLでスレッドリダイレクタが反応したりしており、 URLUtils.isBBS()、URLUtils.isBoard() の見直しが必要です。
http://jbbs.shitaraba.net/bbs/read.cgi/computer/44179/1426703154/761-765
http://jbbs.shitaraba.net/bbs/read.cgi/computer/44179/1435322223/75

**Comment by nodaguti** [comment]
pull req ありがとうございます．

本件について，#294 などによって掲示板固有の設定(どのようなURLが「板」と判断され，どのようなURLが「スレ」と判断されるべきかという本件の問題を含む)はプラグイン化される予定です．
実際，本件は(まだ動作しませんが) feature/#294-new-local-server ブランチにあるプラグインにてすでに考慮に入れられています．

また，URLUtils自体が 1.8.0 で導入されたモジュールです．すなわち，

- 現在リリースされているバージョンには存在しないバグである．
- 開発版にて一旦導入されたが，将来的に削除される予定である．

という状況です．

私は，特に2番目の理由から，本件についてリソースを割くのは適切でないと考えています．
なぜなら，今後別の掲示板に関する同様の不具合が寄せられるたびに，開発版のみで存在し，かつ次リリース時には削除される機能に対してリソースを割く必要が発生するからです．

したがって，本件に係る修正は，URLUtils 内の定数を修正するのではなく，プラグイン化によって修正いたします．

開発版をお使いの方にはご不便をおかけいたしますが，ご理解の程どうぞよろしくお願い致します．
