### ISSUE TITLE
Defaultスキンで特定のIDのカウント処理が行われない

### ISSUE THREAD

**Issue by EarlgreyPicard** [chaika/chaika#306]
０以外の数字が含まれないIDは parseInt() すると ０ となり、IDなしと判定されてカウント処理がスキップされています。
http://jbbs.shitaraba.net/bbs/read.cgi/computer/44179/1435322223/57-58

**Comment by nodaguti** [comment]
根本的な修正が必要．

- BeBaseID がない場合に，`<BEBASEID>` が 0 になってしまうのを修正する
   - これが，ほとんどすべての ID の末尾に 0 がついてしまっている理由です． feature/#294-new-local-server ではすでに修正済みです．
- `isAnonymousID` にて正規表現等によるより正確な判断をするようにする
   - 上記が修正されれば，`/^\s+$/` で判断できるようになると考えています．

**Comment by nodaguti** [comment]
Fixed in d54d6df2c6953cd1da79b673422017a2e4f1c725
