### ISSUE TITLE
e10s対応の書き込みウィザード挙動について

### ISSUE THREAD

**Issue by EarlgreyPicard** [chaika/chaika#315]
chaika: 1.8.0pre.8b05b8fa47197ca1931dedcbff4b73682dc44e6a
制約があって難しいと思いますが一応書いておきます。
たぶん1.8.0で一番不満が出そうなのがこれでしょう。
初期状態ではタブに開くのでスレッドを見ながらレスを作るのに不便です。
browser.link.open_newwindow.restriction=1でウインドウ表示しますが、メインウインドウと同様なウインドウを開いてしまうので、サイドバーやツールバーを多用してるとそれがサブウインドウにも出てしまう。
ためしに wizard.js の window.open() をいじってみましたが featuresとしてサイズやツールバー無しを指定しても全く反映されないのですね。dialog とか指定しちゃうとハングしちゃいますし。

あともう一点、sage のチェックが初期状態では外れているのが気になりました。スレッドごとに記憶されるようではありますが。

**Comment by nodaguti** [comment]
報告ありがとうございます．

いろいろ試してみたのですが，ことごとくうまくいかず，苦肉の策として通常の `window.open` で開いています．

試したもの:

- ProtocolHandler.js 内で，`getMostRecentWindow` 経由で `openDialog` する．

   ```
   let win = Services.wm.getMostRecentWindow(aType);
   win.openDialog('chrome://chaika/content/post/wizard.xul', '_blank', features, ...args);
   ```

   - `win` が `undefined` になってしまい，実行不可．
- ProtocolHandler.js 内で，nsIWindowWatcher 経由で `openWindow` する．([参考](https://developer.mozilla.org/en-US/docs/Working_with_windows_in_chrome_code#Example_4_Using_nsIWindowWatcher_when_you_don%27t_have_a_window_(primitives_only)))

   ```
   let watcher = Cc["@mozilla.org/embedcomp/window-watcher;1"]
                            .getService(Ci.nsIWindowWatcher);
   watcher.openWindow(null, url, '_blank', features, array);
   ```

   - nsIWindowWatcher を取得する部分でエラー
- ProtocolHandler.js 内で GlobalMessageManager を取得し，`chaika-open-chrome-url` のようなメッセージを投げて，chrome プロセス内で `window.openDialog` する．

   - GlobalMessageManager を取得する部分でエラー．

- ProtocolHandler の中身を全て components.js に移し，`sendAsyncMessage` や `sendSyncMessage` で `chaika-open-chrome-url` を投げる

   - `sendAsyncMessage` を呼ぶところでエラー．

- wizard.js 内で `window.openDialog` を呼ぶ

   - そもそも content プロセスでは window オブジェクト以下に `openDialog` 関数は生えていないためエラー．

sage チェックの件についてはちょっと調べてみたいと思います．

**Comment by nodaguti** [comment]
content プロセス内では何ができて何ができないのか，いまいち把握できていなかったのですが，ようやくMDNで記事を見つけました．

e10sに対応しろよ！と大々的に宣伝している割には，解説記事の充実は後回しになっている感じがします... (前に探した時はなかったような印象)

https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Limitations_of_frame_scripts

**Comment by nodaguti** [comment]
改めて `sendAsyncMessage` を使って書き直したところ，今度はなぜかうまくいったので，本件は修正されました．

**Comment by nodaguti** [comment]
そういえば、sageチェックの件調査し忘れていました。
後ほど調査いたします。
