### ISSUE TITLE
複数行選択時のコピー - タイトル と URL と "選択文字列"

### ISSUE THREAD

**Issue by EarlgreyPicard** [chaika/chaika#322]
報告: http://jbbs.shitaraba.net/bbs/read.cgi/computer/44179/1435322223/498
複数行選択状態でコンテキストメニューから選択文字列のコピーをした場合に、選択文字列の改行が連結されて150文字でカットされるという動作。検索とかも一緒？
使ってませんでしたが、たぶん1.8.0preに機能実装された時からこの動作だった模様。

**Comment by nodaguti** [comment]
`nsIContextMenu` 経由での選択文字列取得は，150文字カット等の余計な処理が入っている．
そのため，独自に frame script から選択部分を取ってくる処理を実装する必要がある．

**Comment by EarlgreyPicard** [comment]
nsIContextMenu での選択文字列取得って検索とかするためのものっぽいので、そういう用途では妥当な仕様なのかと思います。今から処理を実装するとかやってる余裕もないかと思いますので、こういう仕様（レス本文の複数行のコピーは想定していない）であるとオンラインヘルプにでも書いておけば十分かな、と私は思います。

**Comment by nodaguti** [comment]
仕様にしてしまいたいのは山々なのですが，選択部分をAAとして保存，などの項目もあるので，改行除去+文字数制限がある状態だとちょっと厳しいんですよね...

**Comment by EarlgreyPicard** [comment]
そこの判断はお任せしますが目処はいかがでしょうか？できることがあれば協力いたします。来月の Firefox 42 のリリースで問題ないようであれば chaika 1.8.0 リリース手続きに入るくらいがタイミングとしてよろしいのではないかと思っています。（あまり遅らせるとリリースタイミングを逸してしまうかも…）

**Comment by EarlgreyPicard** [comment]
thread-agent.js に 選択文字列取得要求のメッセージを出して、content 側で getSelection() で取得し、それをメッセージで返すことで、とりあえずそのままの選択文字列を取得することは実現できました。
