### ISSUE TITLE
[e10s] フラット化したコンテキストメニューで unsafe CPOW usage

### ISSUE THREAD

**Issue by EarlgreyPicard** [chaika/chaika#330]
chaika のコンテキストメニューをフラットに設定してマウスで展開させると、コンソールに下記のようなメッセージが多数出力されます。動作には支障ない模様。
unsafe CPOW usage nsContextMenu.js:604:6

**Comment by EarlgreyPicard** [comment]
今のところ大量にワーニングが出力されるだけですが、やはり危なげですのでいっそのことフラット化を廃止しちゃってもいいのではないかと私は思います。

**Comment by nodaguti** [comment]
個人的には，この機能を廃止するのはちょっと大きな変更すぎると考えていまして，もし廃止するのならアンケートを取る必要があると思います．そのため，

- CPOW が出ないように修正する (これができればベストだが，難しいかもしれない)
- 将来的に e10s 完全施行の時に使えなくなるというのを周知しておく．

のどちらか2択かなと考えています．

**Comment by nodaguti** [comment]
フラット化の場合のノードを別に予め用意しておくことで，nsContextMenu.js が content プロセスのノードに触らなくて良いようになりました．
副次効果として，コンテキストメニュー周りのコードがシンプルになりました．
